CREATE OR REPLACE TRIGGER ACT2 
BEFORE UPDATE ON EMPLOYEES
FOR EACH ROW

DECLARE

     V_LOCALIDAD locations.city%TYPE;
     V_PAIS countries.country_name%TYPE;
     V_REGION regions.region_name%TYPE;
     V_LOCATION_DEP departments.location_id%TYPE;


BEGIN

    SELECT DEPARTMENTS.LOCATION_ID, LOCATIONS.CITY, countries.country_name, REGIONS.REGION_NAME
    INTO V_LOCATION_DEP, V_LOCALIDAD, V_PAIS, V_REGION
    FROM departments, LOCATIONS, COUNTRIES, REGIONS
    WHERE :OLD.DEPARTMENT_ID = department_id
    AND DEPARTMENTS.LOCATION_ID = locations.location_id
    AND locations.country_id = countries.country_id
    AND countries.region_id = regions.region_id;


    INSERT INTO EMPLOYEES_H (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID ,SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID, FECHA_DEL_CAMBIO, LOCALIDAD, PAIS, REGION) 
    VALUES (:OLD.EMPLOYEE_ID, :OLD.FIRST_NAME, :OLD.LAST_NAME, :OLD.EMAIL, :OLD.PHONE_NUMBER, :OLD.HIRE_DATE, :OLD.JOB_ID, :OLD.SALARY, :OLD.COMMISSION_PCT, :OLD.MANAGER_ID, :OLD.DEPARTMENT_ID, SYSDATE, 
            V_LOCALIDAD, V_PAIS, V_REGION);

END;